[package]
name = "ngingo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.11.0"
colored = "2.1.0"
serde = { version = "1.0.130", features = ["derive"] }
toml = "0.8.12"
